name: Docker Hub main
on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .docker
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: archidoc422/lpconsole
          tags: |
            type=ref,event=tag
            type=sha
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./.docker/dev_amd64.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          provenance: false
