name: Publish NuGet
on: workflow_dispatch

jobs:
  publish:
    name: Build, Pack & Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        dotnet-quality: 'preview'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Package1
      run: dotnet pack -c Release -o bin LPEssentials/LPEssentials.csproj
    - name: Package2
      run: dotnet pack -c Release -o bin Netsphere/Netsphere.csproj
    - name: Package3
      run: dotnet pack -c Release -o bin CrystalData/CrystalData.csproj
    - name: Package4
      run: dotnet pack -c Release -o bin LP/LP.csproj
      
    - name: Publish
      run: dotnet nuget push bin/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
